### PR TITLE
Port to new Irmin API

### PR DESCRIPTION
**Pull request by samoht**
/cc @BFarinier and @kayceesrk

### CODE REVIEW

**Comment by kayceesrk** [comment]
`Irmin.Merge.promise` invoked [here](https://github.com/mirage/merge-queues/pull/5/files#diff-e86cba1f53bf298fe10c960eea20c439R68) does not exist. Either `promise` function needs to be added to `Irmin.Merge` or the code should be:

     let old () = Lwt.return @@ `Ok (Some (Some queue)) in

**Comment by samoht** [comment]
Needs irmin master. I'll make a release shortly

**Comment by avsm** [comment]
could you cut a release of this now that the new irmin is out?

**Comment by kayceesrk** [comment]
`Irmin.Merge.promise` is not yet available, if I am not mistaken.

**Comment by samoht** [comment]
> Irmin.Merge.promise is not yet available, if I am not mistaken.

It should be in 0.9.4

**Pull request merged**
